osquery/osquery-python

.travis.yml

This ensures the package is up to date and supports 3.5.

Added Python 3.5 to the build matrix

---

.travis.yml

The sudoless workers boot faster and have caching enabled for them for public repositories.

Moved travis workers to the sudoless environment and enabled caching

---

osquery/__init__.py
osquery/management.py
osquery/table_plugin.py

osquery version 1.7.5 has breaking TablePlugin API changes. The new version requires "id" and "op" within route information for table plugins.

Update TablePlugin to use 1.7.5 API

---

.travis.yml

The setup metadata only mentions supporting Python 2x, thus only run tests on CI infrastructure for the respective versions.

Limit TravisCI to Python 2x

---

osquery/__init__.py
osquery/extension_client.py
osquery/extension_manager.py
osquery/management.py

This adds two features:
- Add a thread when the extension manager is started. This watches for the osquery socket to stop.
- Start a thread when the `shutdown` API request occurs. The thread will stop the process within a second.

extensions: Add watchdog thread and open retries

---

README.rst

This PR will add an alternative way of testing an osquery extension quickly.

Adding an alternative testing code in README.rst

---

osquery/__init__.py
osquery/management.py

This attempts to disable the log messages from the `thrift` module. It also adds a 1 second default interval for checking health.

Disable thrift module logging

---

osquery/table_plugin.py
tests/test_table_plugin.py

For `TablePlugins` we need to send all data to Thrift as strings. We allow tables to use `INTEGER` types with SQL, but need to make a fast-pass at converting values which are not string to string-types.
Fixes #28.

table plugin: Convert all values to strings

---

setup.py

Small bugfix for `pip`, `future` is needed for `builtins`.

setup: Add future as a dependency for pip installs

---

README.md

There are two ways to connect to, and use, and osquery process. The most common integration is using the existing `osqueryd` already running on the system. Keep in mind this process is usually running as `root` so your Python code will need similar permissions to connect and use the UNIX domain socket.

readme: Add client example that does not use SpawnInstance

---

osquery/TPipe.py

Windows clients weren't disconnecting correctly, they should simply `CloseHandle`. The `DisconnectNamedPipe` is only for the servers to ensure that subsequent connections go through.

windows: updating close logic for server and client pipes

---

osquery/TPipe.py

The logical fix I had added to correctly disconnect the pipe server was invalid and was causing queries against python extensions to fail. I updated the logic to ensure the client only ever disconnects, which I believe is the correct logic. I'll update with a handle leak test tomorrow to ensure this is the case.

bug: fixing windows extensions not sending responses

---

osquery/management.py

We require compatibility for Python 2.6 internally. This adds a clause that allows us to run extensions on Python 2.6

fix: adding compatibility for python 2.6

---

.travis.yml

It looks like 3.3 is no longer hosted and thus the TravisCI tests fail.

travis: Remove python 3.3 and 3.4 and add 3.7

---

osquery/__init__.py
osquery/management.py

It looks like this implementation has always leaked a file descriptor. When it was changed to support Windows it started leaking two descriptors on macOS and Linux.
This fixes the bug by closing the descriptor in the deconstructor.

management: Fix socket fd leak

---

setup.py

Trying to fix the following dependency issue on Windows platform 😄 
```
>>> import osquery
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\fakepath\AppData\Local\Programs\Python\Python37\lib\site-packages\osquery\__init__.py", line 34, in <module>
from osquery.extension_client import DEFAULT_SOCKET_PATH, ExtensionClient, \
File "C:\Users\fakepath\AppData\Local\Programs\Python\Python37\lib\site-packages\osquery\extension_client.py", line 25, in <module>
from osquery.TPipe import TPipe
File "C:\Users\fakepath\AppData\Local\Programs\Python\Python37\lib\site-packages\osquery\TPipe.py", line 11, in <module>
import win32event
ModuleNotFoundError: No module named 'win32event'
```

Add pywin32 for Windows platform

---

osquery/management.py

Update to WINDOWS_BINARY_PATH so that this works with Chocolatey installs of osQuery (those go to %PROGRAMDATA%) or installs from osquery MSI's (those end up in %ProgramFiles%). Also make use of OS environment variables in case the system isn't installed on the default C:\

WINDOWS_BINARY_PATH Update

---

osquery/management.py

Remove dangling temporary file

---

osquery/table_plugin.py

As described in issue #77, the context information passed to a table plugin's `generate()` method is (a) inconveniently double-encoded and (b) inconsistent in its data type (since it can either be a double-encoded string or an empty dictionary). This PR fixes this to always pass a dictionary, which will contain the unpacked context information if it was provided in the call.

Fix for double-JSON-encoding of table generation contexts (#77)

---

osquery/management.py

I am working on a project where I am using this python library in a Windows and Linux environment. It is super convenient for getting python to communicate with osqueryd.
I am using this module with Python version 3.9 in my environment and I am receiving the following warnings referencing the management.py file:
```
In [1]: from osquery_interface import OsqueryInterface
c:\users\booboy\.virtualenvs\query_app_inf_osquery-dn8tsr2s\src\osquery\osquery\management.py:186: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if status.code is not 0:
c:\users\booboy\.virtualenvs\query_app_inf_osquery-dn8tsr2s\src\osquery\osquery\management.py:243: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if status.code is not 0:
c:\users\booboy\.virtualenvs\query_app_inf_osquery-dn8tsr2s\s …
```

'fix the warnings from 'is not 0' to '!= 0' in management.py

---

osquery/management.py

This resolves an issue where the extension does not shut down if osquery
goes away unexpectedly (without sending a shutdown signal via Thrift).
The scenario could be reliably reproduced by running `osqueryi`,
connecting an extension, and then sending a `SIGKILL` to `osqueryi`. The
exception thrown in the `start_watcher` function would be of type
`thrift.transport.TTransport.TTransportException`, and would cause the
watcher thread to exit without exiting the rest of the program.
This is a possible fix for issues that users have experienced with
extensions reconnecting after the Watchdog kills osquery.

Fix handling of exceptions when osquery goes away

---

osquery/__init__.py
osquery/management.py

Update version numbers for 3.0.7 release

---

setup.py

Including this requirement causes idempotence issues with configuration management systems:
https://www.reddit.com/r/learnpython/comments/uj3dhx/why_does_pip_keep_reinstalling_the_same_version/?rdt=57231
python 3.2 and 2.7 have been end-of-life for several years: https://devguide.python.org/versions/

remove argparse as it was moved to the python standard library as of python 3.2 and python 2.7

---

osquery/management.py

Fix bug with windows binary path management (resolves https://github.com/osquery/osquery-python/issues/91)

Use path join in `management.py`
